name: gh-pages
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    container:
      image: amath583/pages

    steps:
      - name: 'step one'
        shell: bash
      - run: |
          echo "Hello World"
          /bin/ls
          /bin/pwd
          /bin/hostname
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)

  cpu-info:
    runs-on: ubuntu-latest
    name: cpu-info
    container:
      image: amath583/cpu-info

    steps:
      - name: 'step one'
        shell: bash
      - run: |
          echo "Hello World"
          /bin/ls
          /bin/pwd
          /bin/hostname
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)

# jobs:
#   my_job:
#     container:
#       image: node:14.16
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
