name: gh-pages
on:
  push:
  pull_request:

jobs:
  build:
    container:
      image: amath583/cpuinfo

    steps:
      - name step-one
        shell: bash
	run: |
	  echo "Hello World"
	  /bin/ls
	  
# jobs:
#   my_job:
#     container:
#       image: node:14.16
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
