name: gh-pages
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    container: amath583/gh-pages
    steps:
      - name: 'step one'
        run: |
          echo "Hello World"
          /bin/ls -la /usr/local/bin
          /bin/pwd
          /bin/hostname
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)
      - name: 'step two'
        uses: actions/checkout@master
        with:
          fetch-depth: 0 #
      - name: 'check'
        run: |
          /bin/pwd
          /bin/ls -la
	  cd doc-src/sphinx ; make html

# cpuinfo:
#   runs-on: ubuntu-latest
#   name: cpuinfo
#   container: amath583/cpuinfo
#   steps:
#     - run: |
#         echo "Hello World"
#         /bin/ls -la /usr/local/bin
#         /bin/pwd
#         /bin/hostname
#         echo "'uname -s' is:"
#         echo "uname: " $(uname)
#         echo "uname -m: " $(uname -m)
#         echo "uname -r:" $(uname -r)
#         echo "uname -s: " $(uname -s)
#         echo "uname -v: " $(uname -v)
#       name: 'step one'


# jobs:
#   my_job:
#     container:
#       image: node:14.16
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
